### ISSUE TITLE
Create sample Jekyll site and deploy to Github

### ISSUE THREAD

**Issue by duleorlovic** [trkin/kindergarten-exchange#1]
Create sample Jekyll project and put the link of you repository in the comment.
Add Bootstrap (you can use cdn), but since we will use Tailwind, you can practice adding that.
Here is some reference https://mzrn.sh/2022/04/09/starting-a-blank-jekyll-site-with-tailwind-css-in-2022/

**Comment by DeusCorona** [comment]
https://github.com/DeusCorona/JekyllBlog

**Comment by duleorlovic** [comment]
Let's keep this open while we look at all Jekyll blog... we will find the best, and easiest solution hopefully.

**Comment by DeVuDeveloper** [comment]
https://github.com/DeVuDeveloper/jekyll-tailwind/pull/2

**Comment by duleorlovic** [comment]
https://github.com/duleorlovic/tailwind_play_responsive_dark_mode
preview on https://github.com/duleorlovic/tailwind_play_responsive_dark_mode

**Comment by Orlovic982** [comment]
This is my jekyll kindergarten site, on GitHub pages. 
https://orlovic982.github.io/kindergarten
For now is empty, but I will add things spontaneously. Nav bar and stuff

**Comment by duleorlovic** [comment]
Nice sites, I like that @DeVuDeveloper used Netlify (so we can ask him if the client need that).
I also like his [README](https://github.com/DeVuDeveloper/jekyll-tailwind) so I also recorded a video put on my [README](https://github.com/duleorlovic/tailwind_play_responsive_dark_mode). I think it helps a lot in explanation (idea for my repo is that user can use it to develop tailwind while looking at responsive and dark variation at the same time).

I found in all repositories that commit message is poor, so in the future please try to put the short reason why that change was created.

On next meeting we can screenshare what we did and set up next tasks.

After playing with Tailwind and plain Rails forms, we will start using https://docs.stimulusreflex.com/

**Comment by duleorlovic** [comment]
I see that style is loaded from root
![Screenshot from 2023-03-07 14-14-35](https://user-images.githubusercontent.com/1426092/223432950-df986bb3-d614-4ac8-83a8-b31c39a4a965.png)
Try to use [relative_url](https://github.com/duleorlovic/tailwind_play_responsive_dark_mode/blob/main/_layouts/default.html#L7)

**Comment by DeusCorona** [comment]
Sharing a deployment problem I've had with GH actions and way to fix it: https://github.com/duleorlovic/tailwind_play_responsive_dark_mode/issues/1

**Comment by DeusCorona** [comment]
After 11 consecutive deployments, the blog is finally working.
Blog: https://deuscorona.github.io/JekyllBlog/
Source: https://github.com/DeusCorona/JekyllBlog
Important note: I had to add url and baseurl to _config.yml, not just _config.production.

**Comment by duleorlovic** [comment]
Nice submissions.
Thank you @DeVuDevelope, you did the most, production ready site, using `data`, adding google analytics.

I suggest also to try Decap CMS (Netlify CMS) so client can add and remove pages without knowing the git.

**Comment by DeVuDeveloper** [comment]
https://github.com/DeVuDeveloper/jekyll-tailwind/pull/4
Dobro jutro team :)
Uradjen je Netlify CMS. Detalju u PR.
