### ISSUE TITLE
Add rubocop

### ISSUE THREAD

**Issue by duleorlovic** [trkin/kindergarten-exchange#10]
https://github.com/rubocop/rubocop

**Comment by DeVuDeveloper** [comment]
Dobro jutro.
Sefe mogao bi mi napravit par zadataka u kanban da imam nesto da radim
danas.
A ako dozvolis mogao bih dovrsit usera i naravit style za devise forms i
napravit slanje poruka za verifikaciju i reset passworda.
I jedno pitanje, zasto je user samo za development.

**Comment by duleorlovic** [comment]
This is solved by adding Standard gem
