### ISSUE TITLE
Tailwindcss issue with navbar

### ISSUE THREAD

**Issue by DeusCorona** [trkin/kindergarten-exchange#23]
Technicaly not a problem where screensize doesn't change. However, on mobile phones or tablets, changing from standard resolution to landscape can have unforseen consequences when coupled with .js interaction (if menu navbar on mobile is closed and we transition to desktop/landscape resolution, menu buttons will be invisible).

Problem was solved by custom .js function that periodicaly checked the resolution of the screen, but it would be interesting to see it in stimulus.

**Comment by duleorlovic** [comment]
Can you provide example code ?
You can provide it in separate branch.
We can show/hide without javascript code, only depending on screen size.

**Comment by DeusCorona** [comment]
JS code: 
var toggle = true;
var navbarMenuButton = document.getElementById("navbar__menuButton");
var navbarCloseButton = document.getElementById("navbar__closeButton");
var navbar = document.getElementById("navbar");
var faqParagraph = document.getElementsByClassName("FAQParagraph");
var faqButton = document.getElementsByClassName("FAQButton");
navbarMenuButton.addEventListener("click",navbarToggle);
navbarCloseButton.addEventListener("click",navbarToggle);

for(let i = 0; i < faqButton.length; i++)
{
    faqButton[i].addEventListener("click", function(){
        if(faqParagraph[i].style.display === "block" )
        {
            faqParagraph[i].style.display = "none";
        }else
        {
            faqParagraph[i].style.display = "block";
        }
    });
}

function navbarToggle()
{
    if(toggle === false)
    {
        navbar.style.display = "none";
        toggle = true;
    }else
    {
        navbar.style.display = "block";
        toggle = false;
    }
}

function fixTailwind()
{
    if(window.screen.availWidth >= 768)
    {
        navbar.style.display = "block";
        toggle = false;
    }
    setTimeout(fixTailwind, 1000);
}

fixTailwind();

NavBar:
<nav>
			  <div class="flex flex-row justify-between items-center text-white bg-gray-600 px-[1rem] py-[1rem] sm:px-[1.5rem] sm:py-[1.5rem]">
				  <%= link_to "Root", root_path %>
				  <ul class="fixed hidden md:block right-0 top-0 md:relative md:flex-row md:justify-between" id="navbar">
					  <div class="flex flex-col md:flex-row gap-4 md:gap-0 md:mt-0 px-[1rem] py-[1rem] sm:px-[1.5rem] sm:py-[1.5rem] md:p-0 min-h-[100vh] md:min-h-0 min-w-[40vw] md:min-w-0 bg-gray-600/[0.95] z-1 md:z-0 rounded-lg">
						  <li class="md:hidden text-left cursor-pointer" id="navbar__closeButton">
							  <span class="material-symbols-rounded hover:text-blue-400">
								  close
							  </span>
						  </li>
              <hr class="md:hidden">
              <li>
                <a class="hover:bg-blue-400 hover:text-white p-2 md:p-3 rounded-md hover:underline cursor-pointer" href="#">About</a>
              </li>
              <hr class="md:hidden">
              <li>
                <a class="hover:bg-blue-400 hover:text-white p-2 md:p-3 rounded-md hover:underline cursor-pointer" href="#">FAQ</a>
              </li>
              <hr class="md:hidden">
              <li>
                <a class="hover:bg-blue-400 hover:text-white p-2 md:p-3 rounded-md hover:underline cursor-pointer" href="#">Send a request</a>
              </li>
              <hr class="md:hidden">
              <li>
                <a class="hover:bg-blue-400 hover:text-white p-2 md:p-3 rounded-md hover:underline cursor-pointer" href="#">Contact</a>
              </li>
              <hr class="md:hidden">
              <li>
                <% if current_user.present? %>
                  <span data-test="current-user-email"><%= current_user.email %></span>
                  <%= button_to "Sign out", destroy_user_session_path, method: :delete, form_class: "" %>
                <% else %>
                  <%= link_to "Login", new_user_session_path %>
                <% end %>                              
              </li>
						  <hr class="md:hidden">
					  </div>
				  </ul>
          <div class="md:hidden cursor-pointer" id="navbar__menuButton">
            <span class="material-symbols-rounded">
              menu
            </span>
          </div>
         </div>			
     </nav>

**Comment by DeusCorona** [comment]
JS file:
var toggle = true;
var navbarMenuButton = document.getElementById("navbar__menuButton");
var navbarCloseButton = document.getElementById("navbar__closeButton");
var navbar = document.getElementById("navbar");
var faqParagraph = document.getElementsByClassName("FAQParagraph");
var faqButton = document.getElementsByClassName("FAQButton");
navbarMenuButton.addEventListener("click",navbarToggle);
navbarCloseButton.addEventListener("click",navbarToggle);

for(let i = 0; i < faqButton.length; i++)
{
    faqButton[i].addEventListener("click", function(){
        if(faqParagraph[i].style.display === "block" )
        {
            faqParagraph[i].style.display = "none";
        }else
        {
            faqParagraph[i].style.display = "block";
        }
    });
}

function navbarToggle()
{
    if(toggle === false)
    {
        navbar.style.display = "none";
        toggle = true;
    }else
    {
        navbar.style.display = "block";
        toggle = false;
    }
}

function fixTailwind()
{
    if(window.screen.availWidth >= 768)
    {
        navbar.style.display = "block";
        toggle = false;
    }
    setTimeout(fixTailwind, 1000);
}

fixTailwind();

Goes with index.html.erb. Javascript overloads the usual tailwind breakpoint behaviour.
Alternate realization would be generating more html code where navbar menu for desktop and mobile/tablet would be separate divs.

**Comment by DeusCorona** [comment]
@mankec @duleorlovic Here's a branch with demo: https://github.com/trkin/kindergarten-exchange/tree/playing_around
If you remove the periodic js function and close the dropdown menu nav, and afterwards you switch to desktop screensize, navbar won't be visible.
