### ISSUE TITLE
Remove active_admin?

### ISSUE THREAD

**Issue by duleorlovic** [trkin/kindergarten-exchange#32]
Can we use `admin?` method  instead ?
Do you have rubocop plugin in your editor.
My us showing two warnings
![Screenshot 2023-03-29 at 10 18 00](https://user-images.githubusercontent.com/1426092/228471615-9e4c1aa5-e778-4650-b43d-f47433947345.png)

**Comment by duleorlovic** [comment]
Please add standard[ to your ide ](https://github.com/testdouble/standard/wiki)and provide screenshot (similar to my) that it works.

**Comment by DeVuDeveloper** [comment]
Hi, it was in the branch you approved. And you said gem 'standard' only. Ok, something is on top of something, I am not sure, robocop or standard. Standard didn't cry and robocop  I see did.
Standard and Rubocop gems have bit different settings. I see it is possible to do it with admin, but not checked yet.

**Comment by DeVuDeveloper** [comment]
https://github.com/trkin/kindergarten-exchange/pull/45

**Comment by DeVuDeveloper** [comment]
https://github.com/trkin/kindergarten-exchange/pull/50
Removed Active Admin.
