### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by DeusCorona** [trkin/kindergarten-exchange#40]
Error:
PagesControllerTest#test_should_get_index:
ActionView::Template::Error: Error: Function rgb is missing argument $green.
        on line 3 of stdin
>> ue-400{--tw-border-opacity:1;border-color:rgb(96 165 250/var(--tw-border-opa
   ------------------------------------------^

    app/views/layouts/application.html.erb:9
    test/controllers/pages_controller_test.rb:5:in `block in <class:PagesControllerTest>'

rails test test/controllers/pages_controller_test.rb:4

**Comment by duleorlovic** [comment]
I think this was temporary CI issue. Now CI works for https://github.com/trkin/kindergarten-exchange/pull/22
