### ISSUE TITLE
Const file raises an error

### ISSUE THREAD

**Issue by duleorlovic** [trkin/kindergarten-exchange#47]
When I run `rake` this error is shown
```
Failure/Error: require_relative "../config/environment"

SystemExit:
  exit
# ./config/initializers/const.rb:4:in `<main>'
```

**Comment by DeVuDeveloper** [comment]
I can't understand why you copy/paste a complete file from another project that we don't need at all.
Please use the lib folder for constants as we might need plugins if applications grow.

**Comment by duleorlovic** [comment]
Thanks, this is solved https://github.com/trkin/kindergarten-exchange/pull/48
